/**
 * Amounts above 2^53, against values the Python reference produced.
 *
 * These are the two failures the README's Limits section described: a policy whose id differed
 * between the implementations, and a channel update whose signature the Python node could not
 * verify. Both came from `number`. The vectors are generated by foliant/crypto.py, so a pass here
 * is agreement with the reference rather than with ourselves.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { KeyPair, Signed, canonical, hashObj, parseJsonBig } from "../src/crypto.js";
import { Policy, PolicyViolation } from "../src/agent.js";

const RAW = readFileSync(new URL("./vectors.json", import.meta.url), "utf8");
// read with the library's own parser: JSON.parse would round these vectors while loading them
const v = parseJsonBig(RAW) as any;
const POLICY = v.big_integers.policy;
const UPDATE = v.big_integers.update;

describe("integers above 2^53", () => {
  it("is not readable with JSON.parse, which is why parseJsonBig exists", () => {
    const lossy = JSON.parse(RAW).big_integers.policy.dict;
    expect(String(lossy.expiry)).not.toBe("18446744073709551615");
    expect(BigInt(POLICY.dict.expiry)).toBe(18446744073709551615n);
  });

  it("writes the digits Python writes, where String() would write 1e+21", () => {
    expect(String(1e21)).toBe("1e+21"); // what the old code emitted
    expect(canonical(POLICY.dict)).toBe(POLICY.canonical);
    expect(canonical({ a: 10n ** 21n })).toBe('{"a":1000000000000000000000}');
  });

  it("computes the policy id the ledger computes, at 18 decimals", () => {
    expect(hashObj(POLICY.dict)).toBe(POLICY.id);
    expect(Policy.fromDict(POLICY.dict).id).toBe(POLICY.id);
    // and survives the round trip the client makes on every refresh()
    expect(Policy.fromDict(Policy.fromDict(POLICY.dict).toDict()).id).toBe(POLICY.id);
  });

  it("admits the exact 2^64-1 expiry the schema names", () => {
    expect(Policy.fromDict(POLICY.dict).expiry).toBe(2n ** 64n - 1n);
  });

  it("signs a channel update Python verifies, and verifies Python's", () => {
    const mine = KeyPair.fromSeed("alice").signObj(UPDATE.body);
    expect(mine).toBe(UPDATE.signature); // Ed25519 is deterministic
    expect(new Signed(UPDATE.body, Signed.fromDict(UPDATE as never).signer, UPDATE.signature).valid()).toBe(true);
  });

  it("refuses a number that has already lost digits rather than hashing it", () => {
    expect(() => canonical({ a: 1e21 })).toThrow(/pass a bigint/);
    expect(() => canonical({ a: 2 ** 53 + 2 })).toThrow(/pass a bigint/);
    expect(canonical({ a: 2 ** 53 - 1 })).toBe('{"a":9007199254740991}');
  });

  it("refuses a policy amount given as a number", () => {
    const asNumbers = { ...POLICY.dict, per_tx_max: 5e18 };
    expect(() => Policy.fromDict(asNumbers)).toThrow(PolicyViolation);
    expect(() => Policy.fromDict(asNumbers)).toThrow(/must be a bigint, not a number/);
  });
});
